<a href="https://colab.research.google.com/github/VaaniAgarwal/GoogleColab/blob/main/MLTask.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Task 1:
Import the diabetes dataset to your platform from the link given below and perform the following

In [157]:
import pandas as pd
df=pd.read_csv("diabetes_prediction_dataset.csv")

1. Create a data frame and display the number of samples and features with the datatype

In [158]:
print(f"Samples: {df.shape[0]}")
print(f"Features: {df.shape[1]}")
type(df)
df.info()

Samples: 100000
Features: 9
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 9 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   gender               100000 non-null  object
 1   age                  100000 non-null  float64
 2   hypertension         100000 non-null  int64
 3   heart_disease        100000 non-null  int64
 4   smoking_history      100000 non-null  object
 5   bmi                  100000 non-null  float64
 6   HbA1c_level          100000 non-null  float64
 7   blood_glucose_level  100000 non-null  int64
 8   diabetes             100000 non-null  int64
dtypes: float64(3), int64(4), object(2)
memory usage: 6.9+ MB

2. Count the number of diabetes patient who never smoke

In [159]:
never_smoke=df[(df['smoking_history']=='never') & (df['diabetes']==1)].shape[0]
print(f"Number of diabetes patients who never spoke: {never_smoke}")

Number of diabetes patients who never spoke: 3346

3. Display all the statistical measure about the data frame

In [160]:
print(f"Statistical measure:\n{df.describe()}")

Statistical measure:
                 age  hypertension  heart_disease            bmi  \
count  100000.000000  100000.00000  100000.000000  100000.000000
mean       41.885856       0.07485       0.039420      27.320767
std        22.516840       0.26315       0.194593       6.636783
min         0.080000       0.00000       0.000000      10.010000
25%        24.000000       0.00000       0.000000      23.630000
50%        43.000000       0.00000       0.000000      27.320000
75%        60.000000       0.00000       0.000000      29.580000
max        80.000000       1.00000       1.000000      95.690000

         HbA1c_level  blood_glucose_level       diabetes
count  100000.000000        100000.000000  100000.000000
mean        5.527507           138.058060       0.085000
std         1.070672            40.708136       0.278883
min         3.500000            80.000000       0.000000
25%         4.800000           100.000000       0.000000
50%         5.800000           140.000000       0.000000
75%         6.200000           159.000000       0.000000
max         9.000000           300.000000       1.000000

4. Find the number of samples having missing values

In [161]:
missing_values=df.isnull().sum()
print(f"Number of samples having missing values:\n{missing_values}")

Number of samples having missing values:
gender                 0
age                    0
hypertension           0
heart_disease          0
smoking_history        0
bmi                    0
HbA1c_level            0
blood_glucose_level    0
diabetes               0
dtype: int64

5. Print the first 50 samples from the dataset

In [162]:
print(f"First 50 samples:\n{df.head(50)}")

First 50 samples:
    gender   age  hypertension  heart_disease smoking_history    bmi  \
0   Female  80.0             0              1           never  25.19
1   Female  54.0             0              0         No Info  27.32
2     Male  28.0             0              0           never  27.32
3   Female  36.0             0              0         current  23.45
4     Male  76.0             1              1         current  20.14
5   Female  20.0             0              0           never  27.32
6   Female  44.0             0              0           never  19.31
7   Female  79.0             0              0         No Info  23.86
8     Male  42.0             0              0           never  33.64
9   Female  32.0             0              0           never  27.32
10  Female  53.0             0              0           never  27.32
11  Female  54.0             0              0          former  54.70
12  Female  78.0             0              0          former  36.05
13  Female  67.0             0              0           never  25.69
14  Female  76.0             0              0         No Info  27.32
15    Male  78.0             0              0         No Info  27.32
16    Male  15.0             0              0           never  30.36
17  Female  42.0             0              0           never  24.48
18  Female  42.0             0              0         No Info  27.32
19    Male  37.0             0              0            ever  25.72
20    Male  40.0             0              0         current  36.38
21    Male   5.0             0              0         No Info  18.80
22  Female  69.0             0              0           never  21.24
23  Female  72.0             0              1          former  27.94
24  Female   4.0             0              0         No Info  13.99
25    Male  30.0             0              0           never  33.76
26    Male  67.0             0              1     not current  27.32
27    Male  40.0             0              0          former  27.85
28    Male  45.0             1              0           never  26.47
29    Male  43.0             0              0           never  26.08
30  Female  53.0             0              0         No Info  31.75
31    Male  50.0             0              0         No Info  25.15
32  Female  41.0             0              0         current  22.01
33  Female  20.0             0              0           never  22.19
34  Female  76.0             0              0           never  23.55
35    Male   5.0             0              0         No Info  15.10
36  Female  15.0             0              0         No Info  21.76
37  Female  26.0             0              0           never  21.22
38    Male  50.0             1              0         current  27.32
39  Female  34.0             0              0           never  56.43
40    Male  73.0             0              0          former  25.91
41    Male   5.0             0              0         No Info  27.32
42  Female  77.0             1              1           never  32.02
43  Female  66.0             0              0         No Info  29.30
44  Female  67.0             0              0         No Info  27.32
45  Female  44.0             0              0           never  24.93
46  Female  29.0             0              0           never  19.95
47  Female  60.0             0              0           never  18.03
48  Female  38.0             0              0           never  28.27
49  Female   3.0             0              0         No Info  19.27

    HbA1c_level  blood_glucose_level  diabetes
0           6.6                  140         0
1           6.6                   80         0
2           5.7                  158         0
3           5.0                  155         0
4           4.8                  155         0
5           6.6                   85         0
6           6.5                  200         1
7           5.7                   85         0
8           4.8                  145         0
9           5.0                  100         0
10          6.1                   85         0
11          6.0                  100         0
12          5.0                  130         0
13          5.8                  200         0
14          5.0                  160         0
15          6.6                  126         0
16          6.1                  200         0
17          5.7                  158         0
18          5.7                   80         0
19          3.5                  159         0
20          6.0                   90         0
21          6.2                   85         0
22          4.8                   85         0
23          6.5                  130         0
24          4.0                  140         0
25          6.1                  126         0
26          6.5                  200         1
27          5.8                   80         0
28          4.0                  158         0
29          6.1                  155         0
30          4.0                  200         0
31          4.0                  145         0
32          6.2                  126         0
33          3.5                  100         0
34          5.0                   85         0
35          5.8                   85         0
36          4.5                  130         0
37          6.6                  200         0
38          5.7                  260         1
39          6.2                  200         0
40          9.0                  160         1
41          6.6                  130         0
42          5.0                  159         0
43          4.8                  159         0
44          3.5                  160         0
45          6.1                  100         0
46          5.0                   90         0
47          4.0                  159         0
48          6.2                  155         0
49          6.5                  100         0

Task 2:

1. Find the number of missing samples for each feature and if there is any missing value found, then fill the values based on the type of data(continuous/discrete)

In [163]:
missing_values=df.isnull().sum()
print(missing_values)
df['hypertension'].fillna(df['hypertension'].mode(),inplace=True)
df['age'].fillna(df['age'].median(),inplace=True)
df.head(7)

gender                 0
age                    0
hypertension           0
heart_disease          0
smoking_history        0
bmi                    0
HbA1c_level            0
blood_glucose_level    0
diabetes               0
dtype: int64

<ipython-input-163-51e4084f4c2f>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['hypertension'].fillna(df['hypertension'].mode(),inplace=True)
<ipython-input-163-51e4084f4c2f>:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['age'].fillna(df['age'].median(),inplace=True)

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,Female,80.0,0,1,never,25.19,6.6,140,0
1,Female,54.0,0,0,No Info,27.32,6.6,80,0
2,Male,28.0,0,0,never,27.32,5.7,158,0
3,Female,36.0,0,0,current,23.45,5.0,155,0
4,Male,76.0,1,1,current,20.14,4.8,155,0
5,Female,20.0,0,0,never,27.32,6.6,85,0
6,Female,44.0,0,0,never,19.31,6.5,200,1

2. Remove the duplicated sample from the dataset

In [164]:
print(df.duplicated().sum())
df.drop_duplicates(inplace=True)
print(f"After removing duplicates: {df.shape[0]}")

3854
After removing duplicates: 96146

3. Normalize the input feature “blood_glucose_level” to the range of 0 to 1(Use the appropriate normalization type based on the requirement)

In [165]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
df[['blood_glucose_level']]=scaler.fit_transform(df[['blood_glucose_level']])
print(df[['blood_glucose_level']].head(10))

   blood_glucose_level
0             0.272727
1             0.000000
2             0.354545
3             0.340909
4             0.340909
5             0.022727
6             0.545455
7             0.022727
8             0.295455
9             0.090909

4. Map all the categorical data to ordinal data.

In [166]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
df['gender']=encoder.fit_transform(df['gender'])
df['smoking_history']=encoder.fit_transform(df['smoking_history'])
df.head(20)

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,0,80.0,0,1,4,25.19,6.6,0.272727,0
1,0,54.0,0,0,0,27.32,6.6,0.000000,0
2,1,28.0,0,0,4,27.32,5.7,0.354545,0
3,0,36.0,0,0,1,23.45,5.0,0.340909,0
4,1,76.0,1,1,1,20.14,4.8,0.340909,0
5,0,20.0,0,0,4,27.32,6.6,0.022727,0
6,0,44.0,0,0,4,19.31,6.5,0.545455,1
7,0,79.0,0,0,0,23.86,5.7,0.022727,0
8,1,42.0,0,0,4,33.64,4.8,0.295455,0
9,0,32.0,0,0,4,27.32,5.0,0.090909,0
10,0,53.0,0,0,4,27.32,6.1,0.022727,0
11,0,54.0,0,0,3,54.70,6.0,0.090909,0
12,0,78.0,0,0,3,36.05,5.0,0.227273,0
13,0,67.0,0,0,4,25.69,5.8,0.545455,0
14,0,76.0,0,0,0,27.32,5.0,0.363636,0
15,1,78.0,0,0,0,27.32,6.6,0.209091,0
16,1,15.0,0,0,4,30.36,6.1,0.545455,0
17,0,42.0,0,0,4,24.48,5.7,0.354545,0
18,0,42.0,0,0,0,27.32,5.7,0.000000,0
19,1,37.0,0,0,2,25.72,3.5,0.359091,0

5. Identify the outlier range (lower bound and upper bound) for the above dataset and list the outliers.

In [167]:
Q1=df['bmi'].quantile(0.25)
Q3=df['bmi'].quantile(0.75)
IQR=Q3-Q1
lower_bound=Q1-1.5*IQR
upper_bound=Q3+1.5*IQR
print("Lower Bound: ",lower_bound)
print("Upper Bound: ",upper_bound)
df_out=df[df['bmi'].between(lower_bound,upper_bound)]
print(df_out)

Lower Bound:  13.709999999999997
Upper Bound:  39.55
       gender   age  hypertension  heart_disease  smoking_history    bmi  \
0           0  80.0             0              1                4  25.19
1           0  54.0             0              0                0  27.32
2           1  28.0             0              0                4  27.32
3           0  36.0             0              0                1  23.45
4           1  76.0             1              1                1  20.14
...       ...   ...           ...            ...              ...    ...
99994       0  36.0             0              0                0  24.60
99996       0   2.0             0              0                0  17.37
99997       1  66.0             0              0                3  27.83
99998       0  24.0             0              0                4  35.42
99999       0  57.0             0              0                1  22.43

       HbA1c_level  blood_glucose_level  diabetes
0              6.6             0.272727         0
1              6.6             0.000000         0
2              5.7             0.354545         0
3              5.0             0.340909         0
4              4.8             0.340909         0
...            ...                  ...       ...
99994          4.8             0.295455         0
99996          6.5             0.090909         0
99997          5.7             0.340909         0
99998          4.0             0.090909         0
99999          6.6             0.045455         0

[90792 rows x 9 columns]